# Generated by Django 3.2.14 on 2022-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_num',
            field=models.FloatField(blank=True, default=0, unique=True, verbose_name='account num'),
        ),
    ]
